### ISSUE TITLE
Fails on Debian stretch/sid

### ISSUE THREAD

**Issue by schniggie** [videns/vulners-scanner#3]
root@haka:~/vulners-scanner# cat /etc/debian_version
stretch/sid
root@haka:~/vulners-scanner# python --version
Python 2.7.11+
root@haka:~/vulners-scanner# ./lazyScanner.py
Traceback (most recent call last):
  File "./lazyScanner.py", line 85, in <module>
    scanner.auditSystem()
  File "./lazyScanner.py", line 52, in auditSystem
    osInfo = self.getOSInfo()
  File "./lazyScanner.py", line 38, in getOSInfo
    osVersion = re.search("^VERSION_ID=\"?(\w+)\"?",version,re.MULTILINE).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
root@haka:~/vulners-scanner#

**Comment by arkenoi** [comment]
Same on CentOS 6 and on AWS linux. Both lack os-release file. Need a way to fall back to other methods.

**Comment by arkenoi** [comment]
also

./linuxScanner.py 

```
         _
```

__   ___   _| |_ __   ___ _ __ ___
\ \ / / | | | | '_ \ / _ \ '**/ __|
 \ V /| |_| | | | | |  __/ |  \** \
  _/  __,_|_|_| |_|___|_|  |___/

# 

Host info - Host machine
OS Name - rhel, OS Version - 6
Total found packages: 2321
Error - Unknown operation system. Can't find comparator and splitter for packages

**Comment by videns** [comment]
Oh, they dont provide VERSION_ID in debian-stretch. Will try to find a solution. 
Arkenoi, regarding your questions - for linuxScanner issue was fixed, recheck it, please. For missing os-release - basically it should be a problem for linuxScanner, I will recheck. For lazy scanner - its expected behaviour, because the main goal of this script - just demonstrate API features and to work with it

**Comment by videns** [comment]
Fixed stretch scan in linuxScanner. lazyScanner is too lazy for such a big modifications)
Can you recheck, please?

**Comment by schniggie** [comment]
yeah works now. thX

**Comment by videns** [comment]
That's good to hear!
